services:
  mongodb:
    image: mongo:7.0-jammy
    ports: 
      - "27017:27017"
    volumes:
      - db-data:/data/db
    env_file:
      - .env.database
    networks:
      - my-network

volumes:
  db-data:
    driver: local

networks:
  my-network:
    external: true