services:
  nginx: 
    image: nginx:1.31
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - my-network
  my-web:
    image: skillana:1.0.1 #image uri or id
    env_file:
      - .env
    networks:
      - my-network
networks:
  my-network:
    external: true

  